---
- name: create lemurs .lemur directory
  file:
    path: "{{ lemur_home }}/.lemur"
    state: directory
    owner: "{{ lemur_user }}"
    group: "{{ lemur_group }}"
    mode: 0750

- name: change lemur.log ownership
  file:
    path: "{{ lemur_clone_directory }}/lemur.log"
    owner: "{{ lemur_user }}"
    group: "{{ lemur_group }}"
    mode: 0644

- name: generate initial lemur configuration
  command: "su - {{ lemur_user }} -c '/usr/local/bin/venv_exec {{ lemur_binary }} create_config'"
  args:
    chdir: "{{ lemur_clone_directory }}"

- name: copy get_lemur_variables.sh script
  template:
    src: get_lemur_variables.sh.j2
    dest: /usr/local/bin/get_lemur_variables.sh
    owner: root
    group: root
    mode: 0755

- name: get flask SECRET_KEY
  shell: "/usr/local/bin/get_lemur_variables.sh SECRET_KEY"
  register: flask_secret_key

- name: get LEMUR_TOKEN_SECRET
  shell: "/usr/local/bin/get_lemur_variables.sh LEMUR_TOKEN_SECRET"
  register: lemur_token_secret

- name: get LEMUR_ENCRYPTION_KEYS
  shell: "/usr/local/bin/get_lemur_variables.sh LEMUR_ENCRYPTION_KEYS"
  register: lemur_encryption_keys
  
- name: set LEMUR_ENCRYPTION_KEYS fact
  set_fact:
    lemur_encryption_keys_fact: "{{  lemur_encryption_keys.stdout }}"

- name: test template
  template:
    src: lemur.conf.j2
    dest: "{{ lemur_home }}/lemur.conf.j2"

